(load "src/lilschemer.scm")
(in-test-group
  Chapter1
  (define-test (lists-are-not-atoms)
    (define l (list 1 2 3))
    (assert-false (atom? l) "Lists are not atoms")
  )
  (define-test (numbers-are-atoms)
    (assert-true (atom? 3) "Integer numbers are atoms")
    (assert-true (atom? 3.5) "Decimal numbers are atoms")
    (assert-true (atom? 2/3) "Fractional numbers are atoms")
  )
  (define-test (strings-are-atoms)
    (assert-true (atom? "test") "Strings are atoms")
  )
  (define-test (symbols-are-atoms)
    (assert-true (atom? 'a) "Arbitrary symbols are atoms")
  )
)

(in-test-group
  Chapter2
  (define-test (list-of-atoms)
    (define l '(1 2 3))
    (assert-true (lat? l) "List is only composed of atoms")
  )
  (define-test (list-of-not-just-atoms)
    (define l '(1 2 '(3 4)))
    (assert-false (lat? l) "Lists that aren't only atoms return false")
  )
  (define-test (member-of-list)
    (define l '(3 2 1))
    (assert-true (member? 1 l) "1 is a member of l")
  )
)

(in-test-group
  Chapter3:Rember
  (define-test (removes-occurrence)
    (define l '(1 2 3))
    (define out-l '(1 2))
    (assert-equals out-l (rember 3 l) "Removes the only occurrence")
  )
  (define-test (removes-only-first-occurrence)
    (define l '(1 1 1))
    (define out-l '(1 1))
    (assert-equals out-l (rember 1 l) "Removes the first occurrence")
  )
  (define-test (does-no-harm)
    (define l '(1 2 3))
    (assert-equals l (rember 4 l) "Doesn't do anything if the item doesn't exist")
  )
  (define-test (removes-all-occurrences)
    (define l '(1 3 1 4 1))
    (define out-l '(3 4))
    (assert-equals out-l (multirember 1 l) "Multirember removes all occurrences of the atom")
  )
)

(in-test-group
  Chapter3:Firsts
  (define-test (gets-first-from-each-s-expression)
    (define l (list (list 1 2 3) (list 4 5 6) (list 6 7 8)))
    (define out-l (list 1 4 6))
    (assert-equals out-l (firsts l) "Gets the first from each of the nested s-expressions")
  )
)

(in-test-group
  Chapter3:Inserts
  (define-test (inserts-to-the-right)
    (define l '(1 2 4))
    (define out-l '(1 2 3 4))
    (assert-equals out-l (insertRight 3 2 l) "Inserts the new atom after the old one")
  )
  (define-test (inserts-to-the-left)
    (define l '(1 3 4))
    (define out-l '(1 2 3 4))
    (assert-equals out-l (insertLeft 2 3 l) "Inserts the new atom to the left of the old one")
  )
  (define-test (substitutes)
    (define l '(1 5 3))
    (define out-l '(1 2 3))
    (assert-equals out-l (subst 2 5 l) "Replaces the old atom with the new atom")
  )
  (define-test (substitutes-for-the-first-of-two)
    (define l '(1 5 3 6))
    (define out-l '(1 2 3 6))
    (assert-equals out-l (subst2 2 5 6 l) "Replaces the first old atom with the new atom")
  )
  (define-test (substitutes-for-the-second-of-two)
    (define l '(1 6 3 5))
    (define out-l '(1 2 3 5))
    (assert-equals out-l (subst2 2 5 6 l) "Replaces the second old atom with the new atom")
  )
)

(in-test-group
  Chapter3:MultiInsert
  (define-test (inserts-to-the-right-of-each-occurrence)
    (define l '(1 3 1 3 1))
    (define out-l '(1 2 3 1 2 3 1 2))
    (assert-equals out-l (multiInsertRight 2 1 l) "Inserts to the right of each occurrence of an atom")
  )
  (define-test (inserts-to-the-left-of-each-occurrence)
    (define l '(1 3 1 3 1))
    (define out-l '(1 2 3 1 2 3 1))
    (assert-equals out-l (multiInsertLeft 2 3 l) "Inserts to the left of each occurrence of an atom")
  )
  (define-test (replaces-each-occurrence)
    (define l '(1 3 1 3))
    (define out-l '(1 2 1 2))
    (assert-equals out-l (multiSubst 2 3 l) "Replaces the each occurrence of the old atom with the new atom")
  )
)

(in-test-group
  Chapter4:BasicMath
  (define-test (add1-does-that)
    (define x 4)
    (assert-equals 5 (add1 4) "Adds 1")
    (assert-equals 5 (add1 x) "Adds 1")
  )
  (define-test (sub1-does-that)
    (define x 4)
    (assert-equals 3 (sub1 4) "Subtracts 1")
    (assert-equals 3 (sub1 x) "Subtracts 1")
  )
  (define-test (addtup-does-that)
    (define t '(1 2 3))
    (assert-equals 6 (addtup t) "Adds all of the numbers in the tuple")
  )
  (define-test (tupplus-does-its-job)
    (define t1 '(1 2 3))
    (define t2 '(3 2 1))
    (assert-equals '(4 4 4) (tup+ t1 t2) "Adds each of the members of the tuple to the equivalent member")
  )
  (define-test (tupplus-does-its-job-for-unbalanced-tuples)
    (define t1 '(1 2 3))
    (define t2 '(3 2 1 4))
    (assert-equals '(4 4 4 4) (tup+ t1 t2) "Should handle unbalanced tuples too")
  )
  (define-test (length-does-its-job)
    (define l '(1 2 3))
    (assert-equals 3 (length l) "Counts the number of atoms in a list")
  )
  (define-test (pick-does-its-job)
    (define l '(5 4 3 2 1))
    (assert-equals 1 (pick 5 l) "Picking the 5th atom should return 1")
  )
  (define-test (rempick-does-its-job)
    (define l '(5 4 6 2 1))
    (assert-equals '(5 4 2 1) (rempick 3 l) "Pick all except pick")
  )
  (define-test (no-nums-does-its-job)
    (define l '(5 "the" 4 "answer" 4 3))
    (assert-equals '("the" "answer") (no-nums l) "Only the non-numeric atoms remain")
  )
  (define-test (all-nums-does-its-job)
    (define l '(5 "the" 4 "answer" 4 3))
    (assert-equals '(5 4 4 3) (all-nums l) "Only the numeric atoms remain")
  )
  (define-test (equiv-atoms-does-its-job)
    (assert-true (equiv-atoms 2 2) "numbers of the same value are the same")
    (define x 2)
    (assert-true (equiv-atoms x 2) "numbers and atoms that share the same value are the same")
    (assert-false (equiv-atoms x 3) "numbers and atoms that don't share the same value are different")
    (assert-false (equiv-atoms 3 2) "numbers that are different are in fact different")
    (assert-true (equiv-atoms "test" 3) "Numbers and other kinds of atoms are different")
  )
  (define-test (occurs-does-its-job)
    (define l '(1 1 1 1))
    (assert-equals 4 (occurs 1 l) "counts the number of occurrences properly")
  )
  (define-test (is-one-does-its-job)
    (assert-true (is-one? 1) "the number one is one")
    (define x 1)
    (assert-true (is-one? x) "atoms with a value of one are one")
    (assert-false (is-one? 3) "other values are not one")
  )
  (define-test (rempick2-does-its-job)
    (define l '(5 4 3 2 1))
    (assert-equals '(5 3 2 1) (rempick2 2 l) "remove second atom")
  )
)
